### ISSUE TITLE
Publish

### ISSUE THREAD

**Issue by brettz9** [tc39/proposal-accessible-object-hasownproperty#14]
How about publishing the package to let folks make use of the polyfill? You already have the `main` field, etc. Thanks!

**Comment by ljharb** [comment]
@brettz9 TC39 does not publish official polyfills, and nobody should be using a polyfill prior to stage 3.

Once it reaches stage 3 (hopefully this week) I'm sure a number of polyfills will become available. I certainly plan to publish one in the es-shims ecosystem.

**Comment by jamiebuilds** [comment]
Yeah, the polyfill is here as an example of how to implement it. There is a list in the [Implementations](https://github.com/tc39/proposal-accessible-object-hasownproperty#implementations) section of the readme, feel free to add others there

**Comment by ljharb** [comment]
The proposal is now stage 3; https://npmjs.com/object.hasown is published.
