### ISSUE TITLE
Suggested Q&A entry: why not `Reflect.*`?

### ISSUE THREAD

**Issue by mathiasbynens** [tc39/proposal-accessible-object-hasownproperty#2]

**Comment by jamiebuilds** [comment]
Maybe someone can clarify the purpose of `Reflect` to me because my understanding is that it was more a place to intercept implicit operations (`defineProperty`, `setPrototypeOf`) or create functions for syntax features (`new` or `in`). I don't think `has` / `hasOwnProperty` fits within that.

**Comment by ljharb** [comment]
Reflect's purpose is indeed only to contain, 1:1, a method for each Proxy trap. `Reflect.hasOwnProperty` and `Object.has` are already identical, so adding it to Reflect wouldn't make much sense.

**Comment by jridgewell** [comment]
> Reflect.hasOwnProperty and Object.has are already identical, so adding it to Reflect wouldn't make much sense.

`Reflect.has` already exists, and it is the same as `in` operator (own and inherited properties). `Reflect.hasOwnProperty` also exists, and it's inherited from `Object.prototype`, so it has the same requirement to `.call`.

**Comment by ljharb** [comment]
ahhh yes, thanks.
